name: Build checking

on:
  push:
    branches: development
  pull_request:
    branches: development
  workflow_dispatch:

jobs:
  check-build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Yarn install
        run: yarn install
        
      - name: Check build
        run: yarn build
        
      - name: Build the docker image
        run: docker build .