name: Deploy to hosting

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  docker-hub-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.WEB_IMAGE }}:latest

  hosting-deploy:
    needs: docker-hub-deploy
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy to hosting via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTING }}
          username: ${{ secrets.HOSTING_USER }}
          password: ${{ secrets.HOSTING_PASS }}
          script: |
            cd ~/projects/quizlet-clone-next
            sudo docker-compose stop
            sudo docker-compose pull
            sudo env APP_ENV=${{ vars.APP_ENV }} API_HOST=${{ secrets.API_HOST }} NEXT_PUBLIC_APP_HOST=${{ vars.NEXT_PUBLIC_APP_HOST }} \
              NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }} \
              GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              GIT_AUTH_CLIENT_ID=${{ secrets.GIT_AUTH_CLIENT_ID }} GIT_AUTH_CLIENT_SECRET=${{ secrets.GIT_AUTH_CLIENT_SECRET }} \
              OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} LANGCHAIN_API_KEY=${{ secrets.LANGCHAIN_API_KEY }} LANGCHAIN_ENDPOINT=${{ secrets.LANGCHAIN_ENDPOINT }} \
              LANGCHAIN_TRACING_V2=${{ secrets.LANGCHAIN_TRACING_V2 }} LANGCHAIN_PROJECT=${{ secrets.LANGCHAIN_PROJECT }} TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }} \
              docker-compose up -d
            sudo docker image prune -f
